name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  # When Pull Request is merged
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  Deploy-Workers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g lerna
      - run: npm install
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: lerna run deploy --since=${{ github.event.pull_request.base.sha }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
