name: Cloudflare Workers Monorepo Deployment
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  Deploy-Workers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - name: Deploy from the push event
        run: npx lerna run deploy --since=${{ github.event.before }}
        if: github.event_name == 'push'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: Deploy from pull_request event
        run: npx lerna run deploy --since=${{ github.event.pull_request.base.sha }}
        if: github.event_name == 'pull_request'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
