name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

# on:
#   # When Pull Request is merged
#   pull_request:
#     branches:
#       - main
#     types: [closed]

on:
  push:
    branches:
      - main

jobs:
  Deploy-Workers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # - run: npm install -g lerna
      - run: npm install
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: npx lerna run deploy --since='${{ github.event.before }}'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
